name: Xolayhaber Bot

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  calistir:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kütüphane yükle
        run: pip install -r requirements.txt

      - name: Botu çalıştır
        run: python main.py
